branches:
  only:
    - master
env:
  global:
    - secure: "kvDRPADb1ZIp+gpeXYdqwSAkc/ylqfdDpfWKHHVOjm1Q5QkAokRQPRbjgEz/gjwy25WxRKpc+Im9Tm7z33gxOeLAQNcI9FEGHP3kT4Sfts1tkmF+nc3nG5snhfffUt5jpGvQFimKds/Yr/MkbgUjQooQ8wSwdFGppwGJxoLGdhGbBKzhk6AEa2DyLafT49ilGl81nkty8FA6kPTAlI5pmCdxF7AEtt7o2KFbWSng7Lf2o7RkRzDujhU+QuHl0ZAqZu62/g/OLpesn3F1kt5jg2Azf0/tqx9NSCe4Pfr0eUtBTwEIv+tdX9YbUhxrBndB0EhOXaapmEO71HCZc+rRDeLdBZLRM56nwfLFkDc3sO8+V7XhqxLzWiZwbpZ+9aDx6dOmGiwCNFW9RsJVoGs3VHWC2xDLVPjmbrlDqEngqbO+r9dgwsyaDKle6+2HdChoTjDusQGrtUPfXPFeCAIFsOD69qWgywvzeO/joSk8FUb64QjGmHi0dNYO+igRraZRqRQGyub8kU5GqcFD0h402Mz14UrZ0zxJBRh3JABiS04Zh4Hg7Zlqp44IdBN+6X9k4DtirkCKTa18ViMt4+tFRIo0EQeZPVPN3ZgJatoztlDxsDEcXELCx8M85lUbh7Wg2FDY73r1WhCQuKyd1tqtPqIVmM0sK4tgM+lxQJRlRck="

install:
  - bundle
script: jgd -u http://KosmonautX:$PASSWORD@github.com/KosmonautX/blog.git

